version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE_URL=psql://root:root@db:5432/catalog
    command: "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=catalog
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432


