# Generated by Django 4.2.4 on 2023-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=3, max_digits=11)),
                ("cost", models.DecimalField(decimal_places=3, max_digits=11)),
                ("image", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
