version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE_URL=psql://root:root@db:5433/user_notification
      - DJANGO_SETTINGS_MODULE=user_email_notification.settings
    command: "python manage.py runserver 0.0.0.0:8001"

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=user_notification
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
